### ISSUE TITLE
scrlayer-scrpage.sty Missing \endcsname inserted.<to be read again> \textwidth \KOMAProcessOptions

### ISSUE THREAD

**Issue by mkoedding** [jneug/schule#2]
Guten Morgen,

ich versuche nun schon seit zwei Tagen, die Tex-Dateien für die Lerntheken zu verwenden, jedoch kommt bei mir immer der Fehler aus dem Titel. 

![2021-11-09 12_45_10-Document _ F__Desktop_schule-master_Mathematik_Brüche_6 1-LT-Bruchrechnung tex](https://user-images.githubusercontent.com/89444003/140918424-3adeb6a8-9c19-4621-ac3d-123404b4ec0b.png)

Ich habe es bisher auf Windows, Mac und auf zwei Linux-Distributionen getestet und mit MikTex, als auch TexLive.

Hattest du das Problem schonmal und weißt, wie man es lösen kann? Die Dokumente der Klasse Arbeitsblätter funktionieren bei mir ohne Probleme.

LG Marvin

**Comment by mkoedding** [comment]
Guten Abend,

ich habe heute gesehen, dass die Klasse Arbeitsblatt den Typ Lerntheke schon vorsieht, aber dieser Typ noch nicht implementiert ist. Wird Lerntheke als Dokumententyp noch erscheinen?

LG Marvin

**Comment by mkoedding** [comment]
Hallo Problem gelöst. Falls noch jemand mal das Problem haben sollte - Hier:

**Lösung**: In der Datei _ngb.lerntheke.code.tex_ `\RequirePackage[automark,headwidth=\textwidth]{scrlayer-scrpage}` ändern zu `\RequirePackage[automark,headwidth=195mm]{scrlayer-scrpage}`

Damit hat es bei mir funktioniert. Die 195mm kann man wahrscheinlich noch verfeinern, aber damit geht es wenigstens. Ansonsten ist das ein sehr mächtiges Paket. Ich bin froh, darauf gestoßen zu sein. 

LG Marvin

**Comment by jneug** [comment]
Hallo Marvin, danke für die Infos. Ich plane die Lerntheken bald umzusetzen, aber Momentan lag zu viel anderes an. 
Danke schonmal für den schnellen Fix.

**Comment by jneug** [comment]
Mit der aktuellen Version vom [arbeitsblatt-Paket](https://github.com/jneug/arbeitsblatt) können die Lerntheken nun gesetzt werden. Es gibt noch einige Warnmeldungen und nicht passende Farben, aber im großen und ganzen klappt es.
