### ISSUE TITLE
Textbreite in der Lerntheke

### ISSUE THREAD

**Issue by Lio2210** [jneug/schule#3]
Lieber Herr Neugebauer, 
mit großer Begeisterung habe ich Ihre LateX-Vorlage für Lerntheken entdeckt. Trotz LateX-Kenntnissen und durchforsten der ganzen einzelnen Dateien, kann ich leider nicht rausfinden, warum der Text bei mir immer noch ein paar cm breit gesetzt wird und ich daher natürlich auch eine Menge "overfull \hbox" Fehler bekomme. 
Haben Sie einen Tipp für mich, wo ich schauen könnte? Vielleicht habe ich irgendwo eine Einstellung übersehen. Wobei ich eigentlich an den Dateien erstmal nichts geändert, sondern sie nur kopiert habe.

Vielen Dank!

![image](https://user-images.githubusercontent.com/94862177/142912965-6c9d5f4c-52cb-43e8-80c6-2f128db9e468.png)

![image](https://user-images.githubusercontent.com/94862177/142913186-4a481b94-f314-4358-b786-d888d87b4c61.png)

**Comment by jneug** [comment]
Hallo, ich gucke mir das gerne mal an. Die Vorlage für die Lerntheke ist derzeit in Überarbeitung, weil ich derzeit vom [Schule-Paket](https://ctan.org/pkg/schule) auf [meine eigene Variante](https://github.com/jneug/arbeitsblatt) umsteige. Daher habe ich die Lerntheken mit den aktuellen Paketversionen nicht getestet. Auf den ersten Blick gibt es da einige Inkompatibilitäten. 
Ich hoffe, dass ich demnächst dazu komme, die Lerntheken für mein neues Paket umzuarbeiten und dann wieder leichter nutzbar zu machen.

**Comment by jneug** [comment]
So lange kannst du mal hier gucken: #2

**Comment by jneug** [comment]
Mit der aktuellen Version vom [arbeitsblatt-Paket](https://github.com/jneug/arbeitsblatt) können die Lerntheken nun gesetzt werden. Es gibt noch einige Warnmeldungen und nicht passende Farben, aber im großen und ganzen klappt es. Entsprechend habe ich die vorhandenen Lerntheken umgestellt und die PDFs neu erzeugt.
